# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.0.1
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: media
  name: media
spec:
  containers:
  - command:
    - /init
    env:
    - name: PGID
      value: "1000"
    - name: PUID
      value: "1000"
    - name: TZ
      value: Europe/Prague
    image: lscr.io/linuxserver/radarr:latest
    name: radarr
    ports:
    - containerPort: 7878
      hostPort: 7878
      protocol: TCP
    volumeMounts:
    - mountPath: /config
      name: nfs-video-radarr
    - mountPath: /movies
      name: nfs-video-movies
    - mountPath: /downloads
      name: nfs-video-downloads
    - mountPath: /incomplete-downloads
      name: nfs-video-incomplete
  - command:
    - /init
    env:
    - name: GUID
      value: "1000"
    - name: TZ
      value: Europe/Prague
    - name: PUID
      value: "1000"
    image: lscr.io/linuxserver/sonarr:latest
    name: sonarr
    ports:
    - containerPort: 8989
      hostPort: 8989
      protocol: TCP
    volumeMounts:
    - mountPath: /config
      name: nfs-video-sonarr
    - mountPath: /tv
      name: nfs-video-series
    - mountPath: /downloads
      name: nfs-video-downloads
    - mountPath: /incomplete-downloads
      name: nfs-video-incomplete
  - command:
    - /init
    env:
    - name: PGID
      value: "1000"
    - name: PUID
      value: "1000"
    - name: TZ
      value: Europe/Prague
    image: lscr.io/linuxserver/prowlarr:develop
    name: prowlarr
    ports:
    - containerPort: 9696
      hostPort: 9696
      protocol: TCP
    volumeMounts:
    - mountPath: /config
      name: nfs-video-prowlarr
  - command:
    - /init
    env:
    - name: PGID
      value: "1000"
    - name: TZ
      value: Europe/Prague
    - name: PUID
      value: "1000"
    image: lscr.io/linuxserver/bazarr:latest
    name: bazarr
    ports:
    - containerPort: 6767
      hostPort: 6767
      protocol: TCP
    volumeMounts:
    - mountPath: /config
      name: nfs-video-bazarr
    - mountPath: /movies
      name: nfs-video-movies
    - mountPath: /tv
      name: nfs-video-series
  - command:
    - /init
    env:
    - name: WEBUI_PORT
      value: "8080"
    - name: PUID
      value: "1000"
    - name: TZ
      value: Europe/Prague
    - name: PGID
      value: "1000"
    - name: WEBUI_PORT
      value: 8085
    image: lscr.io/linuxserver/qbittorrent:latest
    name: qbittorrent
    ports:
    - containerPort: 8085
      hostPort: 8085
      protocol: TCP
    - containerPort: 6881
      hostPort: 6881
      protocol: TCP
    - containerPort: 6881
      hostPort: 6881
      protocol: UDP
    volumeMounts:
    - mountPath: /incomplete-downloads
      name: nfs-video-incomplete
    - mountPath: /config
      name: nfs-video-qbittorrent
    - mountPath: /downloads
      name: nfs-video-downloads
  - command:
    - /init
    env:
    - name: PGID
      value: "1000"
    - name: PUID
      value: "1000"
    - name: TZ
      value: Europe/Prague
    image: lscr.io/linuxserver/sabnzbd:latest
    name: sabnzbd
    ports:
    - containerPort: 8080
      hostPort: 8084
      protocol: TCP
    volumeMounts:
    - mountPath: /downloads
      name: nfs-video-downloads
    - mountPath: /incomplete-downloads
      name: nfs-video-incomplete
    - mountPath: /config
      name: nfs-video-sabz
  - args:
    - yarn
    - start
    command:
    - /sbin/tini
    - --
    env:
    - name: TZ
      value: Europe/Prague
    image: docker.io/fallenbagel/jellyseerr:latest
    name: jellyseerr
    ports:
    - containerPort: 5055
      hostPort: 5055
      protocol: TCP
    volumeMounts:
    - mountPath: /app/config
      name: nfs-video-jellyseer
  volumes:
  - hostPath:
      path: /nfs/video/radarr
      type: Directory
    name: nfs-video-radarr
  - hostPath:
      path: /nfs/video/movies
      type: Directory
    name: nfs-video-movies
  - hostPath:
      path: /nfs/video/downloads
      type: Directory
    name: nfs-video-downloads
  - hostPath:
      path: /nfs/video/sonarr
      type: Directory
    name: nfs-video-sonarr
  - hostPath:
      path: /nfs/video/series
      type: Directory
    name: nfs-video-series
  - hostPath:
      path: /nfs/video/prowlarr
      type: Directory
    name: nfs-video-prowlarr
  - hostPath:
      path: /nfs/video/bazarr
      type: Directory
    name: nfs-video-bazarr
  - hostPath:
      path: /nfs/video/qbittorrent
      type: Directory
    name: nfs-video-qbittorrent
  - hostPath:
      path: /nfs/video/incomplete
      type: Directory
    name: nfs-video-incomplete
  - hostPath:
      path: /nfs/video/sabz
      type: Directory
    name: nfs-video-sabz
  - hostPath:
      path: /nfs/video/jellyseer
      type: Directory
    name: nfs-video-jellyseer
